#this is for normal test data
[tenant5]
username= piyushd+lwp+rm2@valuefy.com
password= Piyush@123456


[tenant42]
username= piyushd+rm42@m5wealth.com
password= Piyush@123

;[client-tenant5]
;username = HFSA6807
;password = Pass@123

# this is for 2fa test data
[tenant3]
username= Omkarb+sys@valuefy.com
password= Pass@1234

[staging-creds]
url = https://app-staging.wealthfy.com/login
username= piyushd+lwp+rm2@valuefy.com
password= Piyush@123456

[Test-creds]
url = https://app-test-staging.wealthfy.com/
username= piyushd+lwp+rm2@valuefy.com
password= Piyush@123456


[Dev-creds]
url = https://app-dev-staging.wealthfy.com/login
username = Omkarb+rm@valuefy.com
password = Pass@1234

[env-test_Client-tenant5]
username = SZJZ4207
password = Pass@123

#this creds for test env and tenant 5
[client-tenant5]
username = SZJZ4207
password = Pass@123

